title:        Asger Sommer
tagline:      'Asger Sommer (Sommer717)'
description:  'A blog about code, design and games.'
url:          http://asgersommer.com
version:      1.1.1
author:
  name:       ''
  email:      ''
permalink:    pretty
markdown:     redcarpet
highlighter:  rouge
paginate:     5
gems:         [jekyll-paginate]