# Description
title:            Asger Sommer
description:      'A blog about code, science and design.'
baseurl:          ""
url:              https://asgersommer.com
# enforce_ssl:    asgersommer.com
twitter_username: AsgerSommer
github_username:  AsgerSommer

version:          1.0.0
author:
  name:           Asger Sommer
  url:            https://twitter.com/AsgerSommer
github:
  repo:           https://github.com/AsgerSommer/asgersommer.github.io

# Setup
markdown:         kramdown
highlighter:      rouge
plugins:  
  - jekyll-sitemap           
  - jekyll-paginate
  - jemoji
sass:
  style:          :compressed
permalink:        pretty
paginate:         5
paginate_path:    "/blog/page:num/"
baseurl:          ""




