# Description
title:            Asger Sommer
description:      'A blog about code, science and design.'
url:              http://asgersommer.com
version:          1.0.0
author:
  name:           Asger Sommer
  url:            https://twitter.com/AsgerSommer
github:
  repo:           https://github.com/AsgerSommer/asgersommer.github.io

# Setup
markdown:         kramdown
highlighter:      rouge
gems:  
  - jekyll-sitemap           
  - jekyll-paginate
  - jemoji
sass:
  style:          :compressed
permalink:        pretty
paginate:         5
baseurl:          ""




