title:        Asger Sommer
tagline:      'Asger Sommer'
description:  'A blog about code, science and design.'
url:          http://asgersommer.com
version:      1.1.1
author:
  name:       'Asger Sommer'
  email:      ''
permalink:    pretty
markdown:     redcarpet
highlighter:  rouge
paginate:     5
gems:         [jekyll-paginate]