# Description
title:            Asger Sommer
description:      'A blog about code, science and design.'
baseurl:          "" # apparently this breaks github pages serve of jekyll
url:              https://asgersommer.com
enforce_ssl:    asgersommer.com
twitter_username: AsgerSommer
github_username:  AsgerSommer

version:          1.0.0
author:
  name:           Asger Sommer
  url:            https://asgersommer.com
github:
  repo:           https://github.com/AsgerSommer/asgersommer.github.io

# Setup
markdown:         kramdown
highlighter:      rouge
plugins:  
  - jekyll-sitemap           
  - jemoji
sass:
  style:          :compressed
permalink:        pretty
gems:
  - jekyll-paginate-v2

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: /:year/:month/:title.html
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# tag cloud
tag_page_layout: tag_page
tag_page_dir: tag